### ISSUE TITLE
How to get vocab.txt file?

### ISSUE THREAD

**Issue by ghost** [suderoy/PREREQ-IAAI-19#2]
Hi,
How did you get the vocab.txt file? Is it derived from cs_preq.csv? 
Thanks!

**Comment by suderoy** [comment]
For the scope of the paper it is considered as given, that is, you know the concept space. There are many ways to extract the vocab from cs_preq though. The method is generally known as  key phrase extraction/ concept extraction. It needs to be an extractive method than abstractive to work in this case.

**Comment by ghost** [comment]
Thanks!
